version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: nuxt_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev -- --host 0.0.0.0
    environment:
      - NODE_ENV=development
    restart: always
