spring:
  application:
    name: api
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:lumina}?currentSchema=${DB_SCHEMA:general}
    username: ${DB_USER:luminar}
    password: ${DB_PASSWORD:}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: ${DB_SCHEMA:general}
    default-schema: ${DB_SCHEMA:general}
    baseline-on-migrate: true
    callbacks:
      - com.example.api.infrastructure.config.AfterMigrateCallback
  messages:
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: false
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://keycloak:8080/realms/lumina/protocol/openid-connect/certs}

logging:
  level:
    com.example.api.presentation.GlobalExceptionHandler: DEBUG

server:
  port: 8081
  servlet:
    context-path: /api/v1
