-- ============================================
-- V1: usersテーブル作成
-- ============================================

-- スキーマの作成（存在しない場合）
CREATE SCHEMA IF NOT EXISTS general;

-- usersテーブルの作成
CREATE TABLE general.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    idp_subject VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    name VARCHAR(100) NOT NULL,
    timezone VARCHAR(50) NOT NULL DEFAULT 'Asia/Tokyo',
    created_by BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NOT NULL DEFAULT 0,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 主キー制約
ALTER TABLE general.users ADD CONSTRAINT pk_users PRIMARY KEY (id);

-- ユニークキー制約: idp_subject
ALTER TABLE general.users ADD CONSTRAINT uk_users_idp_subject UNIQUE (idp_subject);

-- ユニークキー制約: email
ALTER TABLE general.users ADD CONSTRAINT uk_users_idp_email UNIQUE (email);

-- インデックス作成（パフォーマンス最適化）
CREATE INDEX idx_users_idp_subject ON general.users(idp_subject);
CREATE INDEX idx_users_email ON general.users(email);