-- ============================================
-- V3: employees, employee_departmentsテーブル作成
-- ============================================

-- employeesテーブルの作成
CREATE TABLE general.employees (
    employee_number VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    status VARCHAR(50) NOT NULL DEFAULT 'ENABLED',
    created_by BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NOT NULL DEFAULT 0,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 主キー制約
ALTER TABLE general.employees ADD CONSTRAINT pk_employees PRIMARY KEY (employee_number);

-- インデックス作成（パフォーマンス最適化）
CREATE INDEX idx_employees_name ON general.employees(name);

-- employee_departmentsテーブルの作成
CREATE TABLE general.employee_departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    employee_number VARCHAR(50) NOT NULL,
    department_code VARCHAR(50) NOT NULL,
    is_primary BOOLEAN NOT NULL DEFAULT false,
    version BIGINT NOT NULL DEFAULT 0,
    created_by BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NOT NULL DEFAULT 0,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 主キー制約
ALTER TABLE general.employee_departments ADD CONSTRAINT pk_employee_departments PRIMARY KEY (id);

-- 外部キー制約: employees
ALTER TABLE general.employee_departments ADD CONSTRAINT fk_emp_dept_employee 
    FOREIGN KEY (employee_number) REFERENCES general.employees(employee_number);

-- 外部キー制約: departments
ALTER TABLE general.employee_departments ADD CONSTRAINT fk_emp_dept_department 
    FOREIGN KEY (department_code) REFERENCES general.departments(code);

-- 複合ユニークキー制約: 従業員と部署の組み合わせ
ALTER TABLE general.employee_departments ADD CONSTRAINT uk_emp_dept_emp_dept 
    UNIQUE (employee_number, department_code);

-- インデックス作成（パフォーマンス最適化）
CREATE INDEX idx_emp_dept_employee ON general.employee_departments(employee_number);
CREATE INDEX idx_emp_dept_department ON general.employee_departments(department_code);